apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.3.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            # Chuyển đổi sang bộ nhớ tạm, không tạo PVC đòi hỏi StorageClass nữa
            storageSpec:
              emptyDir: {}
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

        grafana:
          # Tắt hoàn toàn tính năng lưu trữ ổ cứng vật lý
          persistence:
            enabled: false
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

        alertmanager:
          service:
            type: LoadBalancer
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true