apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.3.1
    helm:
      values: |
        prometheus:
          prometheusSpec:
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: "premium-rwo"
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 10Gi
          # Giữ mặc định ClusterIP cho service của Prometheus

        grafana:
          initChownData:
            enabled: false
          podSecurityContext:
            fsGroup: 472
            runAsGroup: 472
            runAsUser: 472
          persistence:
            enabled: true
            size: 5Gi
            storageClassName: "premium-rwo"
          service:
            type: LoadBalancer
            annotations:
              # Ép AWS tạo Public Load Balancer để có link Demo
              service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

        # Bỏ phần ghi đè service của Alertmanager để giữ mặc định (ClusterIP)

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
