apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: shoppingassistantservice
  labels:
    app: shoppingassistantservice
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: shoppingassistantservice
      previewService: shoppingassistantservice-preview
      autoPromotionEnabled: false

  selector:
    matchLabels:
      app: shoppingassistantservice

  template:
    metadata:
      labels:
        app: shoppingassistantservice

    spec:
      serviceAccountName: shoppingassistantservice
      terminationGracePeriodSeconds: 5

      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

      containers:
        - name: server
          image: harbor.thenttthytlu.io.vn/sample-microservice/shoppingassistantservice:latest
          ports:
            - containerPort: 8080

          readinessProbe:
            periodSeconds: 5
            grpc:
              port: 8080

          livenessProbe:
            periodSeconds: 5
            grpc:
              port: 8080

          env:
            - name: PORT
              value: "8080"
            - name: DISABLE_PROFILER
              value: "1"

          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi

      imagePullSecrets:
        - name: harbor-pull-secret