apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/nt114thenttthytlu/gitops-for-microservices-demo
    path: kyverno/policies 
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # BẮT BUỘC cho Kyverno policies để tránh lỗi size
