apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  selector:
    app.kubernetes.io/name: currencyservice
    app.kubernetes.io/instance: currencyservice
  ports:
    - name: grpc
      port: 7000
      targetPort: 7000